---
# tasks file for install_docker
- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
    filename: docker
    update_cache: yes

- name: Install Docker Engine
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
  notify: restart docker
