#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL
  CREATE USER grafana_user WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
  CREATE DATABASE grafana WITH OWNER grafana_user ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;
  ALTER ROLE grafana_user WITH PASSWORD 'grafanapasswd';
  GRANT ALL PRIVILEGES ON DATABASE "grafana" TO grafana_user;
EOSQL
